# Generated by Django 6.1.1 on 2026-09-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Empresa')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True, verbose_name='Identificador na URL')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas/logos/', verbose_name='Logo da Empresa')),
                ('cor_primaria', models.CharField(default='#2563EB', help_text='Ex: #2563EB (Azul)', max_length=7, verbose_name='Cor Primária (Hex)')),
                ('cor_secundaria', models.CharField(default='#1E40AF', help_text='Ex: #1E40AF', max_length=7, verbose_name='Cor Secundária (Hex)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nome'],
            },
        ),
    ]
